
services:

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis-ui:
    image: redis/redisinsight:latest
    container_name: redis-ui
    ports:
      - "5540:5540" 
    volumes:
      - redisinsight_data:/data 
    depends_on:
      - redis

volumes:
  redis_data:
  rabbitmq_data:
  redisinsight_data:
