<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10" />
		<PackageReference Include="Scrutor" Version="7.0.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.3.1" />
		<PackageReference Include="Supabase" Version="1.1.1" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
		<PackageReference Include="System.Threading.RateLimiting" Version="10.0.5" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Enterprise.Flowstate.Core\Enterprise.Flowstate.BAL.csproj" />
	</ItemGroup>

</Project>
